name: BarisKeserTools
version: 1.3.6.4
main: tr.com.havasaldirisi.HavaSaldirisiPlugin
api-version: '1.20'
author: Barış Keser

commands:
  havasaldirisi:
    description: Hava Saldırısı Oltası verir
    permission: bariskesertools.admin
    aliases: [havasaldiri]
  tntsil:
    description: Dünyadaki tüm patlamaya hazır TNT'leri siler
    permission: bariskesertools.admin
    aliases: [tntsil]
  itemsil:
    description: Yerdeki tüm eşyaları siler
    permission: bariskesertools.admin
    aliases: [itemsil]
  eşyayahasarver:
    description: Elinde tuttuğun eşyanın canını (durability) düşürür
    permission: bariskesertools.admin
    aliases: [esyayahasarver]
  tum-envantere-hasar-ver-rasgele:
    description: Envanterindeki tüm hasar alabilen eşyaların durabilitysini rastgele düşürür
    permission: bariskesertools.admin
  chunk-yiyici:
    description: Olta çekildiğinde gökten süzülen ve yeri dibe kadar silen özel TNT oltası verir.
    permission: bariskesertools.admin
  bariskesertools:
    description: Eklenti bilgilerini ve güncellemeleri yönetir.
    permission: bariskesertools.admin
    aliases: [bkt]
  buyuktnt:
    description: Dev boyutlu ve yüksek hasarlı bir TNT fırlatır (Boyut sadece 1.21'de desteklenir).
    permission: bariskesertools.admin
    usage: /buyuktnt [Güç(100-2000)]
  lavaisfloor:
    description: Zemin Lav minigame komutlarını yönetir
    permission: bariskesertools.admin
    usage: /lavaisfloor topla | baslat | kur | sil
  etkinligekatil:
    description: Zemin Lav etkinliğine veya toplanan sunucu etkinliklerine katılır.
    usage: /etkinligekatil
  baris-optimizasyon:
    description: BarisKeser TPS Optimizasyon Menüsünü açar
    permission: bariskesertools.admin
    aliases: [boptimizasyon, tps]
