name: Build & Release

on:
  push:
    paths:
      - 'build.gradle.kts' # Ne zaman build.gradle.kts güncellenirse (versiyon atlarsa) otomatik çalışır
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Extract Version
        id: get_version
        run: |
          VERSION=$(grep -oP 'version\s*=\s*"\K[^"]+' build.gradle.kts)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "BarisKeserTools v${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
